language: node_js #设置语言
 
node_js: 9.10.0 #设置相应的版本
 
install:
 #- set SASS_BINARY_PATH=./linux-x64-47_binding.node & npm install node-sass --save
 - npm install #安装hexo及插件
 - npm install hexo-renderer-jade@0.3.0 --save
 #- npm install hexo-renderer-sass --save
 - npm install hexo-helper-qrcode --save
 #- npm install node-sass --save
script:
 - hexo cl #清除
 - hexo g #生成
 
after_script:
 - cd ./public
 - git init
 - git config user.name "kiikgu" #修改name
 - git config user.email "dingkun.wang@tongdun.cn" #修改email
 - git add .
 - git commit -m "update"
 - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master #GH_TOKEN是在Travis中配置token的名称
 
branches:
 only:
 - master #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
env:
global:
 - GH_REF: github.com/kiikgu/kiikgu.github.io.git #设置GH_REF，注意更改yourname

